version: '3.8'

services:
  frontend-dev:
    container_name: rent-travel-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    platform: linux/amd64
